name: signin
description: "A new Flutter project."
publish_to: "none" # Remove quotes if you want to publish
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.6.0
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.1
  image_picker: ^1.0.8
  image_cropper: ^5.0.1
  path_provider: ^2.1.3
  flutter_image_compress: ^2.2.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/images/default_pfp.jpeg
