// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrB6yMm5GRKhvdA1yhhD4s93bm9LcxRg0',
    appId: '1:934282878778:web:825325f94d30a0f0473a03',
    messagingSenderId: '934282878778',
    projectId: 'houseswap-e9720',
    authDomain: 'houseswap-e9720.firebaseapp.com',
    storageBucket: 'houseswap-e9720.appspot.com',
    measurementId: 'G-NNL64QH01M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxTf2L3ly-JkerhkSXUWKERoIEF6DgXZE',
    appId: '1:934282878778:android:95714bab2691b30e473a03',
    messagingSenderId: '934282878778',
    projectId: 'houseswap-e9720',
    storageBucket: 'houseswap-e9720.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMH9z6qln8A6P2sF9Ck-HSlzvYZHkw0q0',
    appId: '1:934282878778:ios:d17052bc903a5ec8473a03',
    messagingSenderId: '934282878778',
    projectId: 'houseswap-e9720',
    storageBucket: 'houseswap-e9720.appspot.com',
    iosBundleId: 'com.example.signin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMH9z6qln8A6P2sF9Ck-HSlzvYZHkw0q0',
    appId: '1:934282878778:ios:d17052bc903a5ec8473a03',
    messagingSenderId: '934282878778',
    projectId: 'houseswap-e9720',
    storageBucket: 'houseswap-e9720.appspot.com',
    iosBundleId: 'com.example.signin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrB6yMm5GRKhvdA1yhhD4s93bm9LcxRg0',
    appId: '1:934282878778:web:6488d8bcfb900635473a03',
    messagingSenderId: '934282878778',
    projectId: 'houseswap-e9720',
    authDomain: 'houseswap-e9720.firebaseapp.com',
    storageBucket: 'houseswap-e9720.appspot.com',
    measurementId: 'G-EWMRRMKXBE',
  );
}
